services:
  - type: web
    name: mas-news-search
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install chromium --with-deps
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
